version: 2

jobs:
    build:
        environment:
            TZ: "/usr/share/zoneinfo/America/Detroit"
        working_directory: ~/lufo
        docker:
            - image: circleci/buildpack-deps:xenial-browsers
        steps:
            - add_ssh_keys
            - checkout
            - restore_cache:
                keys:
                  - nvm-cache-{{ .Environment.NVM_CACHE_VERSION }}-{{ arch }}-{{ checksum ".nvm" }}
                  - yarn-cache-{{ .Environment.YARN_CACHE_VERSION }}-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "lufo-api/package.json" }}-{{ checksum "lufo-cli/package.json" }}
            - run:
                name: Install nvm/NodeJS/Yarn
                command: |
                  # Install nvm.
                  echo 'Installing nvm...'
                  cd ~
                  [ ! -d ".nvm" ] && git clone https://github.com/creationix/nvm.git .nvm
                  cd .nvm
                  git checkout $NVM_VERSION
                  . nvm.sh
                  # Install NodeJS.
                  echo 'Installing NodeJS versions necessary for testing...'
                  . ~/lufo/.nvm
                  for v in "${LUFO_NODE_VERSIONS[@]}"; do nvm install $v; done
                  nvm alias default $DEFAULT_LUFO_NODE_VERSION
                  # Make nvm available in future shells.
                  echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
                  echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
                  # Install Yarn.
                  curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
                  # Make yarn available in future shells.
                  echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
            - run:
                name: Install project dependenciesfor v in "$(cat .nvm | xargs)";
                command: |
                  yarn
            - run:
                name: Run tests
                command: |
                  . ~/lufo/.nvm
                  for v in "${LUFO_NODE_VERSIONS[@]}"; do TESTEN_VERSIONS="$TESTEN_VERSIONS -n $v"; done
                  yarn run testen $TESTEN_VERSIONS
            - save_cache:
                key: nvm-cache-{{ .Environment.NVM_CACHE_VERSION }}-{{ arch }}-{{ checksum ".nvm" }}
                paths:
                    - /home/circleci/.nvm
                    - /home/circleci/.yarn
            - save_cache:
                key: yarn-cache-{{ .Environment.YARN_CACHE_VERSION }}-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "lufo-api/package.json" }}-{{ checksum "lufo-cli/package.json" }}
                paths:
                    - /home/circleci/lufo/node_modules
