version: 2

jobs:
    build:
        environment:
            TZ: "/usr/share/zoneinfo/America/Detroit"
        working_directory: ~/lufo
        docker:
            - image: circleci/buildpack-deps:xenial-browsers
        steps:
            - add_ssh_keys
            - checkout
            - restore_cache:
                key: nvm-cache-{{ .Environment.NVM_CACHE_VERSION }}-{{ arch }}-{{ checksum ".lufoDependencies" }}
            - restore_cache:
                key: api-yarn-cache-{{ .Environment.YARN_CACHE_VERSION }}-{{ arch }}-{{ checksum "lufo-api/package.json" }}
            - restore_cache:
                key: cli-yarn-cache-{{ .Environment.YARN_CACHE_VERSION }}-{{ arch }}-{{ checksum "lufo-cli/package.json" }}
            - run:
                name: Install nvm/NodeJS/Yarn
                command: |
                  scripts/setup.sh
            - run:
                name: API
                command: |
                  cd lufo-api
                  ../scripts/test.sh
            - run:
                name: CLI
                command: |
                  cd lufo-cli
                  ../scripts/test.sh
                  # Prevent CircleCI caching.
                  ./node_modules/.bin/linklocal -u > /dev/null 2>&1
            - run:
                name: Deploy
                command: |
                  scripts/deploy.sh
            - save_cache:
                key: nvm-cache-{{ .Environment.NVM_CACHE_VERSION }}-{{ arch }}-{{ checksum ".lufoDependencies" }}
                paths:
                    - /home/circleci/.nvm
                    - /home/circleci/.yarn
            - save_cache:
                key: api-yarn-cache-{{ .Environment.YARN_CACHE_VERSION }}-{{ arch }}-{{ checksum "lufo-api/package.json" }}
                paths:
                    - /home/circleci/lufo/lufo-api/node_modules
            - save_cache:
                key: cli-yarn-cache-{{ .Environment.YARN_CACHE_VERSION }}-{{ arch }}-{{ checksum "lufo-cli/package.json" }}
                paths:
                    - /home/circleci/lufo/lufo-cli/node_modules
            - run:
                name: Publish docs
                command: |
                  scripts/docs.sh
